### ISSUE TITLE
Add OAuth / OIDC Support

### ISSUE THREAD

**Issue by mraible** [vishal423/ngx-hipster#12]
It shouldn't be too difficult to add support for JHipster's OAuth 2.0 authentication since most of it happens on the server.

I'd be happy to help implement this feature.

**Comment by vishal423** [comment]
thanks for your interest @mraible. It should be trivial to support an authentication question during the app generation. I will spend some time over the next few days to incorporate it. Thanks

**Comment by vishal423** [comment]
closed by https://github.com/vishal423/ngx-hipster/commit/f3036eec97a5f3bcb7e16cf7c42923b782944f24
